In [5]:
import numpy as np
from operator import add

def slope_aspect(a,d=1.):
    # this seems to get aspect wrong. It might be an array indexing problem.
    i=1
    j=1
    Z1=a[i+1,j-1]
    Z2=a[i+1,j]
    Z3=a[i+1,j+1]
    Z4=a[i,j-1]
    Z5=a[i,j]
    Z6=a[i,j+1]
    Z7=a[i-1,j-1]
    Z8=a[i-1,j]
    Z9=a[i-1,j+1]
    print(Z1,Z2,Z3)
    print(Z4,Z5,Z6)
    print(Z7,Z8,Z9)
    
    A = ((Z1 + Z3 + Z7 + Z9)/4. - (Z2 + Z4 + Z6 + Z8)/2. + Z5)/d**4
    B = ((Z1 + Z3 - Z7 - Z9)/4. - (Z2 - Z8)/2.)/d**3
    C = ((-Z1 + Z3 - Z7 + Z9)/4. + (Z4 - Z6)/2.)/d**3
    D = ((Z4 + Z6)/2. - Z5)/d**2
    E = ((Z2 + Z8)/2. - Z5)/d**2
    F = (-Z1 + Z3 + Z7 - Z9)/(4.*d**2)
    G = (-Z4 + Z6)/(2.*d)
    H = (Z2 - Z8)/(2.*d)
    I = Z5
    
    slope = np.sqrt(G**2 + H**2)
    aspect = np.rad2deg(np.arctan2(-H, -G))
    PrC =  2.*(D*G**2 + E*H**2 + F*G*H)/(G**2 + H**2)
    PlC = -2.*(D*H**2 + E*G**2 - F*G*H)/(G**2 + H**2)
    print(slope,aspect,PrC,PlC)
    
    dydz, dxdz = np.gradient(a)
    slope_mag = np.sqrt(dxdz**2 + dydz**2)
    slope2 = np.pi/2. - np.arctan(slope_mag)
    aspect2 = np.rad2deg( np.arctan2(-dxdz, dydz) )
    print(slope_mag,aspect2)

def mdem( a, dx=1., dy=1. ):
    """
    Curvature equations in MICRODEM
    Not sure what original code was, but might be javascript
    from https://www.usna.edu/Users/oceano/pguth/md_help/html/geomorph_curvature.htm
    
    """
    # Not sure what ASp is, and assume sqr(x) == x**2 
    ASp = 1.
    i=1
    j=1
    Z = a[i,j]
    
    z1=a[i+1,j-1]-Z
    z2=a[i+1,j]-Z
    z3=a[i+1,j+1]-Z
    z4=a[i,j-1]-Z
    z5=0.
    z6=a[i,j+1]-Z
    z7=a[i-1,j-1]-Z
    z8=a[i-1,j]-Z
    z9=a[i-1,j+1]-Z
     
    A = ((z1 + z3 + z4 + z6 + z7 + z9) / 6. - (z2 + z8) / 3.) / dx / dy
    B = ((z1 + z2 + z3 + z7 + z8 + z9) / 6. - (z4 + z6) / 3.) / dx / dy
    C = (z3 + z7 -z1 - z9) / 4.  / dx / dy
    D = (z3 + z6 + z9 - z1 - z4 - z7) / 6. / dx;
    E = (z1 + z2 + z3 - z7 - z8 - z9) / 6. / dy;
    F = (2. * ( z2 + z4 + z6 - z8) - (z1 + z3 + z7 + z9) ) / 9.
    SqABC = np.sqrt( (A-B)**2 + C**2)

    MaxCurve = 20. * (ASp)*(-A - B + SqABC);
    MinCurve = 20. * (ASp)*(-A - B - SqABC);
    SqED = E**2 + D**2
    SlopeCurvature = 0.
    PlanCurvature = 0.
    CrossC = 0.   
    if SqED > 0.000001:
        SlopeCurvature = -200. * (A * D**2 + B * E**2 + C * D * E) / SqED / (1. + SqED)**1.5
        PlanCurvature = 200. * (B * D**2 + A * E**2 - C * D * E) / (1. +SqED)**1.5
        CrossC = -20.* (ASp)*(B*D*D + A*E*E - C*D*E)/  SqED;
 
    print(MaxCurve,MinCurve)
    print(SlopeCurvature,PlanCurvature)
    print(CrossC)
    
#a = np.array([[3,3,3],[5,5,5],[7,7,7]])
#a = np.array([[1,2,3],[1,2,3],[1,2,3]])
a = np.array([[1,1,1],[1,0,1],[1,1,1]])

slope_aspect(a)
mdem(a)   

1 1 1
1 0 1
1 1 1
0.0 -180.0 nan nan
[[ 0.  1.  0.]
 [ 1.  0.  1.]
 [ 0.  1.  0.]] [[  -0. -180.   -0.]
 [  90.   -0.  -90.]
 [  -0.   -0.   -0.]]
-13.3333333333 -13.3333333333
0.0 0.0
0.0


C:\Users\csherwood\AppData\Local\Continuum\Anaconda\envs\IOOS3\lib\site-packages\ipykernel\__main__.py:33: RuntimeWarning: invalid value encountered in double_scalars
C:\Users\csherwood\AppData\Local\Continuum\Anaconda\envs\IOOS3\lib\site-packages\ipykernel\__main__.py:34: RuntimeWarning: invalid value encountered in double_scalars
