In [18]:
import numpy as np
from operator import add

def slope_aspect(a,d=1.):
    # this seems to get aspect wrong. It might be an array indexing problem.
    i=1
    j=1
    Z1=a[i+1,j-1]
    Z2=a[i+1,j]
    Z3=a[i+1,j+1]
    Z4=a[i,j-1]
    Z5=a[i,j]
    Z6=a[i,j+1]
    Z7=a[i-1,j-1]
    Z8=a[i-1,j]
    Z9=a[i-1,j+1]
#     print(Z1,Z2,Z3)
#     print(Z4,Z5,Z6)
#     print(Z7,Z8,Z9)
    
    A = ((Z1 + Z3 + Z7 + Z9)/4. - (Z2 + Z4 + Z6 + Z8)/2. + Z5)/d**4
    B = ((Z1 + Z3 - Z7 - Z9)/4. - (Z2 - Z8)/2.)/d**3
    C = ((-Z1 + Z3 - Z7 + Z9)/4. + (Z4 - Z6)/2.)/d**3
    D = ((Z4 + Z6)/2. - Z5)/d**2
    E = ((Z2 + Z8)/2. - Z5)/d**2
    F = (-Z1 + Z3 + Z7 - Z9)/(4.*d**2)
    G = (-Z4 + Z6)/(2.*d)
    H = (Z2 - Z8)/(2.*d)
    I = Z5
    
    slope = np.sqrt(G**2 + H**2)
    aspect = np.rad2deg(np.arctan2(-H, -G))+90. # +90 is CRS kludge
    PrC =  2.*(D*G**2 + E*H**2 + F*G*H)/(G**2 + H**2)
    PlC = -2.*(D*H**2 + E*G**2 - F*G*H)/(G**2 + H**2)
    print("slope:",slope,'aspect:',aspect,"PrC:",PrC,"PlC:",PlC)
    
    dydz, dxdz = np.gradient(a)
    print("dydz:",dydz)
    print("dxdz:",dxdz)
    slope_mag = np.sqrt(dxdz**2 + dydz**2)
    slope2 = np.degrees( np.pi/2. - np.arctan(slope_mag))
    aspect2 = np.rad2deg( np.arctan2(-dxdz, dydz) )
    print("slope: ", slope)
    print("slope2:", slope2)
    print("slope_mag:", slope2)

    print("aspect: ",aspect)
    print("aspect2:",aspect2)



    
#a = np.array([[3,3,3],[5,5,5],[7,7,7]])
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
#a = np.array([[1,1,1],[1,0,1],[1,1,1]])
print(a)
slope_aspect(a)
print(np.diff(a))

[[1 2 3]
 [1 2 3]
 [1 2 3]]
slope: 1.0 aspect: -90.0 PrC: 0.0 PlC: -0.0
dydz: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
dxdz: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
slope:  1.0
slope2: [[45. 45. 45.]
 [45. 45. 45.]
 [45. 45. 45.]]
slope_mag: [[45. 45. 45.]
 [45. 45. 45.]
 [45. 45. 45.]]
aspect:  -90.0
aspect2: [[-90. -90. -90.]
 [-90. -90. -90.]
 [-90. -90. -90.]]
[[1 1]
 [1 1]
 [1 1]]
